require File.expand_path("../constants", __FILE__)
require File.expand_path("../interface", __FILE__)
require File.expand_path("../domain/railway", __FILE__)
require File.expand_path("../domain/locomotive", __FILE__)
require File.expand_path("../domain/turnout", __FILE__)